In [8]:
#Importing libraries
# !pip install tensorflow
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
import tensorflow as tf
from tensorflow.keras.layers import Dense
from tensorflow.keras import Sequential
from sklearn.metrics import classification_report
import warnings
warnings.filterwarnings('ignore')

In [9]:
#Load the data

In [10]:
df = pd.read_csv('https://raw.githubusercontent.com/aishwaryamate/Datasets/main/Churn_Modelling.csv')
df

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9996,15606229,Obijiaku,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,9997,15569892,Johnstone,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,9998,15584532,Liu,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,9999,15682355,Sabbatini,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
9999,10000,15628319,Walker,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

In [11]:
df.drop(columns=['RowNumber','CustomerId','Surname'], inplace=True)

# Data Transformation

In [12]:
df.isna().sum()

CreditScore        0
Geography          0
Gender             0
Age                0
Tenure             0
Balance            0
NumOfProducts      0
HasCrCard          0
IsActiveMember     0
EstimatedSalary    0
Exited             0
dtype: int64

In [13]:
df

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...
9995,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
9999,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

In [14]:
df.drop(columns = ['Exited'])

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary
0,619,France,Female,42,2,0.00,1,1,1,101348.88
1,608,Spain,Female,41,1,83807.86,1,0,1,112542.58
2,502,France,Female,42,8,159660.80,3,1,0,113931.57
3,699,France,Female,39,1,0.00,2,0,0,93826.63
4,850,Spain,Female,43,2,125510.82,1,1,1,79084.10
...,...,...,...,...,...,...,...,...,...,...
9995,771,France,Male,39,5,0.00,2,1,0,96270.64
9996,516,France,Male,35,10,57369.61,1,1,1,101699.77
9997,709,France,Female,36,7,0.00,1,0,1,42085.58
9998,772,Germany,Male,42,3,75075.31,2,1,0,92888.52
9999,792,France,Female,28,4,130142.79,1,1,0,38190.78

In [15]:
df = pd.get_dummies(data=df, columns=['Geography','Gender'],dtype = int)
df

,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_France,Geography_Germany,Geography_Spain,Gender_Female,Gender_Male
0,619,42,2,0.00,1,1,1,101348.88,1,1,0,0,1,0
1,608,41,1,83807.86,1,0,1,112542.58,0,0,0,1,1,0
2,502,42,8,159660.80,3,1,0,113931.57,1,1,0,0,1,0
3,699,39,1,0.00,2,0,0,93826.63,0,1,0,0,1,0
4,850,43,2,125510.82,1,1,1,79084.10,0,0,0,1,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,771,39,5,0.00,2,1,0,96270.64,0,1,0,0,0,1
9996,516,35,10,57369.61,1,1,1,101699.77,0,1,0,0,0,1
9997,709,36,7,0.00,1,0,1,42085.58,1,1,0,0,1,0
9998,772,42,3,75075.31,2,1,0,92888.52,1,0,1,0,0,1
9999,792,28,4,130142.79,1,1,0,38190.78,0,1,0,0,1,0

# Model Building

In [17]:
df

,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_France,Geography_Germany,Geography_Spain,Gender_Female,Gender_Male
0,619,42,2,0.00,1,1,1,101348.88,1,1,0,0,1,0
1,608,41,1,83807.86,1,0,1,112542.58,0,0,0,1,1,0
2,502,42,8,159660.80,3,1,0,113931.57,1,1,0,0,1,0
3,699,39,1,0.00,2,0,0,93826.63,0,1,0,0,1,0
4,850,43,2,125510.82,1,1,1,79084.10,0,0,0,1,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,771,39,5,0.00,2,1,0,96270.64,0,1,0,0,0,1
9996,516,35,10,57369.61,1,1,1,101699.77,0,1,0,0,0,1
9997,709,36,7,0.00,1,0,1,42085.58,1,1,0,0,1,0
9998,772,42,3,75075.31,2,1,0,92888.52,1,0,1,0,0,1
9999,792,28,4,130142.79,1,1,0,38190.78,0,1,0,0,1,0

In [18]:
sc = StandardScaler()
x = df.drop(columns=['Exited'])
y = df['Exited']

In [19]:
x

,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Geography_France,Geography_Germany,Geography_Spain,Gender_Female,Gender_Male
0,619,42,2,0.00,1,1,1,101348.88,1,0,0,1,0
1,608,41,1,83807.86,1,0,1,112542.58,0,0,1,1,0
2,502,42,8,159660.80,3,1,0,113931.57,1,0,0,1,0
3,699,39,1,0.00,2,0,0,93826.63,1,0,0,1,0
4,850,43,2,125510.82,1,1,1,79084.10,0,0,1,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,771,39,5,0.00,2,1,0,96270.64,1,0,0,0,1
9996,516,35,10,57369.61,1,1,1,101699.77,1,0,0,0,1
9997,709,36,7,0.00,1,0,1,42085.58,1,0,0,1,0
9998,772,42,3,75075.31,2,1,0,92888.52,0,1,0,0,1
9999,792,28,4,130142.79,1,1,0,38190.78,1,0,0,1,0

In [20]:
x = sc.fit_transform(x)
x

array([[-0.32622142,  0.29351742, -1.04175968, ..., -0.57380915,
         1.09598752, -1.09598752],
       [-0.44003595,  0.19816383, -1.38753759, ...,  1.74273971,
         1.09598752, -1.09598752],
       [-1.53679418,  0.29351742,  1.03290776, ..., -0.57380915,
         1.09598752, -1.09598752],
       ...,
       [ 0.60498839, -0.27860412,  0.68712986, ..., -0.57380915,
         1.09598752, -1.09598752],
       [ 1.25683526,  0.29351742, -0.69598177, ..., -0.57380915,
        -0.91241915,  0.91241915],
       [ 1.46377078, -1.04143285, -0.35020386, ..., -0.57380915,
         1.09598752, -1.09598752]])

In [21]:
xtrain,xtest,ytrain,ytest = train_test_split(x,y,test_size=0.20, random_state=1)

In [22]:
xtrain

array([[-0.23310044, -0.94607926, -0.69598177, ..., -0.57380915,
        -0.91241915,  0.91241915],
       [-0.25379399, -0.94607926, -0.35020386, ..., -0.57380915,
         1.09598752, -1.09598752],
       [-0.39864885,  0.77028538,  0.34135195, ..., -0.57380915,
         1.09598752, -1.09598752],
       ...,
       [ 0.22215769,  0.5795782 ,  1.37868567, ..., -0.57380915,
         1.09598752, -1.09598752],
       [ 0.12903671,  0.00745665,  1.03290776, ..., -0.57380915,
         1.09598752, -1.09598752],
       [ 1.16371428,  0.29351742,  0.34135195, ..., -0.57380915,
        -0.91241915,  0.91241915]])

In [23]:
#Initialize model
ann = Sequential()

#Add hidden layer
ann.add(Dense(units=10,activation='relu'))

#Add output layer
ann.add(Dense(units=1, activation='sigmoid'))

#Establish the connection between the layers
ann.compile(optimizer = 'adadelta',loss='binary_crossentropy',metrics='accuracy')

#Fit the data
ann.fit(xtrain,ytrain, epochs=100)

Epoch 1/100
250/250 [==============================] - 1s 2ms/step - loss: 0.7404 - accuracy: 0.5082
Epoch 2/100
250/250 [==============================] - 0s 2ms/step - loss: 0.7396 - accuracy: 0.5090
Epoch 3/100
250/250 [==============================] - 0s 2ms/step - loss: 0.7388 - accuracy: 0.5106
Epoch 4/100
250/250 [==============================] - 0s 2ms/step - loss: 0.7379 - accuracy: 0.5119
Epoch 5/100
250/250 [==============================] - 0s 2ms/step - loss: 0.7371 - accuracy: 0.5131
Epoch 6/100
250/250 [==============================] - 0s 2ms/step - loss: 0.7363 - accuracy: 0.5148
Epoch 7/100
250/250 [==============================] - 0s 2ms/step - loss: 0.7354 - accuracy: 0.5156
Epoch 8/100
250/250 [==============================] - 0s 2ms/step - loss: 0.7345 - accuracy: 0.5174
Epoch 9/100
250/250 [==============================] - 1s 3ms/step - loss: 0.7337 - accuracy: 0.5197
Epoch 10/100
250/250 [==============================] - 0s 1ms/step - loss: 0.7328 - accuracy: 0.5220
Epoch 11/100
250/250 [==============================] - 0s 2ms/step - loss: 0.7320 - accuracy: 0.5235
Epoch 12/100
250/250 [==============================] - 0s 2ms/step - loss: 0.7311 - accuracy: 0.5249
Epoch 13/100
250/250 [==============================] - 0s 2ms/step - loss: 0.7303 - accuracy: 0.5265
Epoch 14/100
250/250 [==============================] - 0s 2ms/step - loss: 0.7295 - accuracy: 0.5279
Epoch 15/100
250/250 [==============================] - 1s 2ms/step - loss: 0.7286 - accuracy: 0.5293
Epoch 16/100
250/250 [==============================] - 1s 3ms/step - loss: 0.7278 - accuracy: 0.5310
Epoch 17/100
250/250 [==============================] - 1s 2ms/step - loss: 0.7269 - accuracy: 0.5326
Epoch 18/100
250/250 [==============================] - 1s 2ms/step - loss: 0.7261 - accuracy: 0.5339
Epoch 19/100
250/250 [==============================] - 1s 3ms/step - loss: 0.7253 - accuracy: 0.5351
Epoch 20/100
250/250 [==============================] - 1s 2ms/step - loss: 0.7244 - accuracy: 0.5368
Epoch 21/100
250/250 [==============================] - 0s 2ms/step - loss: 0.7236 - accuracy: 0.5385
Epoch 22/100
250/250 [==============================] - 0s 2ms/step - loss: 0.7228 - accuracy: 0.5404
Epoch 23/100
250/250 [==============================] - 0s 2ms/step - loss: 0.7220 - accuracy: 0.5422
Epoch 24/100
250/250 [==============================] - 0s 1ms/step - loss: 0.7212 - accuracy: 0.5435
Epoch 25/100
250/250 [==============================] - 0s 2ms/step - loss: 0.7204 - accuracy: 0.5452
Epoch 26/100
250/250 [==============================] - 0s 1ms/step - loss: 0.7196 - accuracy: 0.5476
Epoch 27/100
250/250 [==============================] - 0s 2ms/step - loss: 0.7187 - accuracy: 0.5494
Epoch 28/100
250/250 [==============================] - 0s 2ms/step - loss: 0.7179 - accuracy: 0.5508
Epoch 29/100
250/250 [==============================] - 0s 2ms/step - loss: 0.7171 - accuracy: 0.5526
Epoch 30/100
250/250 [==============================] - 0s 2ms/step - loss: 0.7163 - accuracy: 0.5549
Epoch 31/100
250/250 [==============================] - 0s 1ms/step - loss: 0.7155 - accuracy: 0.5560
Epoch 32/100
250/250 [==============================] - 0s 1ms/step - loss: 0.7148 - accuracy: 0.5571
Epoch 33/100
250/250 [==============================] - 0s 2ms/step - loss: 0.7140 - accuracy: 0.5586
Epoch 34/100
250/250 [==============================] - 0s 2ms/step - loss: 0.7132 - accuracy: 0.5599
Epoch 35/100
250/250 [==============================] - 0s 2ms/step - loss: 0.7124 - accuracy: 0.5614
Epoch 36/100
250/250 [==============================] - 0s 2ms/step - loss: 0.7117 - accuracy: 0.5625
Epoch 37/100
250/250 [==============================] - 0s 2ms/step - loss: 0.7109 - accuracy: 0.5638
Epoch 38/100
250/250 [==============================] - 0s 2ms/step - loss: 0.7101 - accuracy: 0.5656
Epoch 39/100
250/250 [==============================] - 0s 1ms/step - loss: 0.7094 - accuracy: 0.5685
Epoch 40/100
250/250 [==============================] - 0s 2ms/step - loss: 0.7086 - accuracy: 0.5698
Epoch 41/100
250/250 [==============================] - 0s 2ms/step - loss: 0.7078 - accuracy: 0.5719
Epoch 42/100
250/250 [==============================] - 0s 1ms/step - loss: 0.7071 - accuracy: 0.5732
Epoch 43/100
250/250 [==============================] - 0s 2ms/step - loss: 0.7063 - accuracy: 0.5740
Epoch 44/100
250/250 [==============================] - 0s 1ms/step - loss: 0.7056 - accuracy: 0.5751
Epoch 45/100
250/250 [==============================] - 1s 2ms/step - loss: 0.7049 - accuracy: 0.5763
Epoch 46/100
250/250 [==============================] - 1s 2ms/step - loss: 0.7041 - accuracy: 0.5771
Epoch 47/100
250/250 [==============================] - 1s 2ms/step - loss: 0.7034 - accuracy: 0.5784
Epoch 48/100
250/250 [==============================] - 1s 2ms/step - loss: 0.7027 - accuracy: 0.5798
Epoch 49/100
250/250 [==============================] - 1s 2ms/step - loss: 0.7019 - accuracy: 0.5805
Epoch 50/100
250/250 [==============================] - 1s 2ms/step - loss: 0.7012 - accuracy: 0.5821
Epoch 51/100
250/250 [==============================] - 1s 2ms/step - loss: 0.7005 - accuracy: 0.5831
Epoch 52/100
250/250 [==============================] - 1s 2ms/step - loss: 0.6997 - accuracy: 0.5850
Epoch 53/100
250/250 [==============================] - 0s 2ms/step - loss: 0.6990 - accuracy: 0.5871
Epoch 54/100
250/250 [==============================] - 0s 2ms/step - loss: 0.6983 - accuracy: 0.5886
Epoch 55/100
250/250 [==============================] - 0s 2ms/step - loss: 0.6976 - accuracy: 0.5893
Epoch 56/100
250/250 [==============================] - 0s 2ms/step - loss: 0.6969 - accuracy: 0.5905
Epoch 57/100
250/250 [==============================] - 0s 2ms/step - loss: 0.6962 - accuracy: 0.5924
Epoch 58/100
250/250 [==============================] - 0s 2ms/step - loss: 0.6955 - accuracy: 0.5943
Epoch 59/100
250/250 [==============================] - 0s 2ms/step - loss: 0.6947 - accuracy: 0.5951
Epoch 60/100
250/250 [==============================] - 0s 2ms/step - loss: 0.6940 - accuracy: 0.5960
Epoch 61/100
250/250 [==============================] - 0s 2ms/step - loss: 0.6933 - accuracy: 0.5975
Epoch 62/100
250/250 [==============================] - 0s 2ms/step - loss: 0.6927 - accuracy: 0.5985
Epoch 63/100
250/250 [==============================] - 0s 2ms/step - loss: 0.6920 - accuracy: 0.5997
Epoch 64/100
250/250 [==============================] - 0s 2ms/step - loss: 0.6913 - accuracy: 0.6011
Epoch 65/100
250/250 [==============================] - 0s 2ms/step - loss: 0.6906 - accuracy: 0.6026
Epoch 66/100
250/250 [==============================] - 0s 2ms/step - loss: 0.6899 - accuracy: 0.6040
Epoch 67/100
250/250 [==============================] - 0s 1ms/step - loss: 0.6892 - accuracy: 0.6053
Epoch 68/100
250/250 [==============================] - 0s 2ms/step - loss: 0.6886 - accuracy: 0.6071
Epoch 69/100
250/250 [==============================] - 0s 2ms/step - loss: 0.6879 - accuracy: 0.6085
Epoch 70/100
250/250 [==============================] - 0s 2ms/step - loss: 0.6872 - accuracy: 0.6101
Epoch 71/100
250/250 [==============================] - 0s 2ms/step - loss: 0.6866 - accuracy: 0.6109
Epoch 72/100
250/250 [==============================] - 0s 2ms/step - loss: 0.6859 - accuracy: 0.6120
Epoch 73/100
250/250 [==============================] - 0s 2ms/step - loss: 0.6852 - accuracy: 0.6130
Epoch 74/100
250/250 [==============================] - 0s 2ms/step - loss: 0.6846 - accuracy: 0.6140
Epoch 75/100
250/250 [==============================] - 0s 2ms/step - loss: 0.6839 - accuracy: 0.6149
Epoch 76/100
250/250 [==============================] - 0s 2ms/step - loss: 0.6833 - accuracy: 0.6155
Epoch 77/100
250/250 [==============================] - 1s 3ms/step - loss: 0.6826 - accuracy: 0.6165
Epoch 78/100
250/250 [==============================] - 1s 2ms/step - loss: 0.6820 - accuracy: 0.6180
Epoch 79/100
250/250 [==============================] - 0s 2ms/step - loss: 0.6813 - accuracy: 0.6194
Epoch 80/100
250/250 [==============================] - 1s 3ms/step - loss: 0.6807 - accuracy: 0.6206
Epoch 81/100
250/250 [==============================] - 1s 3ms/step - loss: 0.6800 - accuracy: 0.6216
Epoch 82/100
250/250 [==============================] - 1s 3ms/step - loss: 0.6794 - accuracy: 0.6229
Epoch 83/100
250/250 [==============================] - 1s 2ms/step - loss: 0.6787 - accuracy: 0.6236
Epoch 84/100
250/250 [==============================] - 0s 2ms/step - loss: 0.6781 - accuracy: 0.6248
Epoch 85/100
250/250 [==============================] - 0s 2ms/step - loss: 0.6775 - accuracy: 0.6258
Epoch 86/100
250/250 [==============================] - 0s 2ms/step - loss: 0.6769 - accuracy: 0.6275
Epoch 87/100
250/250 [==============================] - 0s 2ms/step - loss: 0.6762 - accuracy: 0.6294
Epoch 88/100
250/250 [==============================] - 0s 2ms/step - loss: 0.6756 - accuracy: 0.6308
Epoch 89/100
250/250 [==============================] - 0s 2ms/step - loss: 0.6750 - accuracy: 0.6310
Epoch 90/100
250/250 [==============================] - 0s 2ms/step - loss: 0.6744 - accuracy: 0.6324
Epoch 91/100
250/250 [==============================] - 0s 2ms/step - loss: 0.6737 - accuracy: 0.6331
Epoch 92/100
250/250 [==============================] - 0s 2ms/step - loss: 0.6731 - accuracy: 0.6352
Epoch 93/100
250/250 [==============================] - 0s 2ms/step - loss: 0.6725 - accuracy: 0.6354
Epoch 94/100
250/250 [==============================] - 0s 2ms/step - loss: 0.6719 - accuracy: 0.6361
Epoch 95/100
250/250 [==============================] - 0s 2ms/step - loss: 0.6713 - accuracy: 0.6375
Epoch 96/100
250/250 [==============================] - 0s 2ms/step - loss: 0.6707 - accuracy: 0.6386
Epoch 97/100
250/250 [==============================] - 0s 2ms/step - loss: 0.6701 - accuracy: 0.6391
Epoch 98/100
250/250 [==============================] - 0s 2ms/step - loss: 0.6695 - accuracy: 0.6401
Epoch 99/100
250/250 [==============================] - 0s 2ms/step - loss: 0.6689 - accuracy: 0.6401
Epoch 100/100
250/250 [==============================] - 0s 2ms/step - loss: 0.6683 - accuracy: 0.6413

In [24]:
xtest

array([[-1.04014895,  0.77028538, -1.04175968, ..., -0.57380915,
        -0.91241915,  0.91241915],
       [ 0.3049319 , -0.4693113 , -0.69598177, ..., -0.57380915,
        -0.91241915,  0.91241915],
       [-1.23673768,  0.29351742, -1.04175968, ..., -0.57380915,
         1.09598752, -1.09598752],
       ...,
       [-0.86425376, -0.4693113 ,  1.72446358, ...,  1.74273971,
        -0.91241915,  0.91241915],
       [-0.30552787, -0.85072567, -1.04175968, ..., -0.57380915,
         1.09598752, -1.09598752],
       [ 0.0462625 ,  1.24705333,  1.37868567, ..., -0.57380915,
        -0.91241915,  0.91241915]])

In [25]:
ypred = ann.predict(xtest)
ypred

63/63 [==============================] - 0s 1ms/step

array([[0.43851808],
       [0.6553819 ],
       [0.23134488],
       ...,
       [0.37597674],
       [0.4436491 ],
       [0.36792377]], dtype=float32)

In [26]:
ytest

9953    0
3850    0
4962    0
3886    0
5437    0
       ..
3919    0
162     0
7903    0
2242    0
2745    0
Name: Exited, Length: 2000, dtype: int64

In [27]:
print(classification_report(ytest,ypred))

ValueError: Classification metrics can't handle a mix of binary and continuous targets

In [28]:
ypred > 0.5

array([[False],
       [ True],
       [False],
       ...,
       [False],
       [False],
       [False]])

In [29]:
ypred = ypred > 0.5
ypred

array([[False],
       [ True],
       [False],
       ...,
       [False],
       [False],
       [False]])

In [ ]:
ytest

In [30]:
print(classification_report(ytest,ypred))

              precision    recall  f1-score   support

           0       0.80      0.75      0.77      1585
           1       0.22      0.27      0.24       415

    accuracy                           0.65      2000
   macro avg       0.51      0.51      0.51      2000
weighted avg       0.68      0.65      0.66      2000

# Hyperparameter Tuning

In [31]:
!pip install -U keras-tuner

Collecting keras-tuner
  Downloading keras_tuner-1.4.7-py3-none-any.whl (129 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 129.1/129.1 kB 1.5 MB/s eta 0:00:00
Requirement already satisfied: keras in /usr/local/lib/python3.10/dist-packages (from keras-tuner) (2.15.0)
Requirement already satisfied: packaging in /usr/local/lib/python3.10/dist-packages (from keras-tuner) (24.1)
Requirement already satisfied: requests in /usr/local/lib/python3.10/dist-packages (from keras-tuner) (2.31.0)
Collecting kt-legacy (from keras-tuner)
  Downloading kt_legacy-1.0.5-py3-none-any.whl (9.6 kB)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests->keras-tuner) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests->keras-tuner) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests->keras-tuner) (2.0.7)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests->keras-tuner) (2024.6.2)
Installing collected packages: kt-legacy, keras-tuner
Successfully installed keras-tuner-1.4.7 kt-legacy-1.0.5

# **Tuning the ANN Model**
- Selecting the best optimizer

In [32]:
import keras_tuner as kt

In [33]:
def optimizer_selection(hp):
    #initialize the model
    model = Sequential()
    #Add hidden layer
    model.add(Dense(units=10, activation='relu'))
    #Add output layer
    model.add(Dense(units=1, activation='sigmoid'))
    #Optimizer selection
    optim = hp.Choice('optimizer', values = ['sgd','adam','rmsprop'])
    model.compile(optimizer=optim, loss = 'binary_crossentropy', metrics = 'accuracy')
    return model

In [34]:
tuner = kt.RandomSearch(
    optimizer_selection,
    objective='val_accuracy',
    max_trials=3
)

In [35]:
tuner.search(xtrain,ytrain, epochs = 3, validation_data = (xtest,ytest))

Trial 3 Complete [00h 00m 03s]
val_accuracy: 0.8199999928474426

Best val_accuracy So Far: 0.8199999928474426
Total elapsed time: 00h 00m 09s

In [36]:
tuner.get_best_hyperparameters()[0].values

{'optimizer': 'rmsprop'}

In [37]:
model = tuner.get_best_models(num_models=1)[0]
model.fit(xtrain,ytrain, epochs = 100, validation_data = (xtest,ytest))

Epoch 1/100
250/250 [==============================] - 1s 3ms/step - loss: 0.4119 - accuracy: 0.8249 - val_loss: 0.4032 - val_accuracy: 0.8265
Epoch 2/100
250/250 [==============================] - 1s 2ms/step - loss: 0.4004 - accuracy: 0.8305 - val_loss: 0.3930 - val_accuracy: 0.8370
Epoch 3/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3909 - accuracy: 0.8371 - val_loss: 0.3851 - val_accuracy: 0.8415
Epoch 4/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3826 - accuracy: 0.8414 - val_loss: 0.3781 - val_accuracy: 0.8450
Epoch 5/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3759 - accuracy: 0.8453 - val_loss: 0.3725 - val_accuracy: 0.8470
Epoch 6/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3706 - accuracy: 0.8484 - val_loss: 0.3690 - val_accuracy: 0.8470
Epoch 7/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3663 - accuracy: 0.8493 - val_loss: 0.3643 - val_accuracy: 0.8510
Epoch 8/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3627 - accuracy: 0.8508 - val_loss: 0.3622 - val_accuracy: 0.8515
Epoch 9/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3599 - accuracy: 0.8519 - val_loss: 0.3585 - val_accuracy: 0.8510
Epoch 10/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3572 - accuracy: 0.8531 - val_loss: 0.3557 - val_accuracy: 0.8545
Epoch 11/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3550 - accuracy: 0.8545 - val_loss: 0.3532 - val_accuracy: 0.8570
Epoch 12/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3533 - accuracy: 0.8543 - val_loss: 0.3517 - val_accuracy: 0.8560
Epoch 13/100
250/250 [==============================] - 1s 4ms/step - loss: 0.3515 - accuracy: 0.8553 - val_loss: 0.3512 - val_accuracy: 0.8555
Epoch 14/100
250/250 [==============================] - 1s 4ms/step - loss: 0.3500 - accuracy: 0.8568 - val_loss: 0.3480 - val_accuracy: 0.8590
Epoch 15/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3490 - accuracy: 0.8570 - val_loss: 0.3468 - val_accuracy: 0.8575
Epoch 16/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3478 - accuracy: 0.8571 - val_loss: 0.3464 - val_accuracy: 0.8560
Epoch 17/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3470 - accuracy: 0.8585 - val_loss: 0.3464 - val_accuracy: 0.8550
Epoch 18/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3463 - accuracy: 0.8581 - val_loss: 0.3444 - val_accuracy: 0.8580
Epoch 19/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3458 - accuracy: 0.8594 - val_loss: 0.3439 - val_accuracy: 0.8585
Epoch 20/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3452 - accuracy: 0.8584 - val_loss: 0.3436 - val_accuracy: 0.8575
Epoch 21/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3447 - accuracy: 0.8580 - val_loss: 0.3426 - val_accuracy: 0.8580
Epoch 22/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3442 - accuracy: 0.8590 - val_loss: 0.3434 - val_accuracy: 0.8590
Epoch 23/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3440 - accuracy: 0.8581 - val_loss: 0.3407 - val_accuracy: 0.8590
Epoch 24/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3434 - accuracy: 0.8590 - val_loss: 0.3408 - val_accuracy: 0.8610
Epoch 25/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3431 - accuracy: 0.8591 - val_loss: 0.3421 - val_accuracy: 0.8595
Epoch 26/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3426 - accuracy: 0.8585 - val_loss: 0.3402 - val_accuracy: 0.8615
Epoch 27/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3422 - accuracy: 0.8586 - val_loss: 0.3400 - val_accuracy: 0.8620
Epoch 28/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3424 - accuracy: 0.8600 - val_loss: 0.3391 - val_accuracy: 0.8610
Epoch 29/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3418 - accuracy: 0.8599 - val_loss: 0.3388 - val_accuracy: 0.8620
Epoch 30/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3417 - accuracy: 0.8600 - val_loss: 0.3386 - val_accuracy: 0.8625
Epoch 31/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3412 - accuracy: 0.8605 - val_loss: 0.3395 - val_accuracy: 0.8615
Epoch 32/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3411 - accuracy: 0.8593 - val_loss: 0.3374 - val_accuracy: 0.8610
Epoch 33/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3407 - accuracy: 0.8595 - val_loss: 0.3391 - val_accuracy: 0.8590
Epoch 34/100
250/250 [==============================] - 1s 4ms/step - loss: 0.3408 - accuracy: 0.8589 - val_loss: 0.3386 - val_accuracy: 0.8610
Epoch 35/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3406 - accuracy: 0.8599 - val_loss: 0.3376 - val_accuracy: 0.8610
Epoch 36/100
250/250 [==============================] - 1s 4ms/step - loss: 0.3403 - accuracy: 0.8605 - val_loss: 0.3389 - val_accuracy: 0.8615
Epoch 37/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3402 - accuracy: 0.8619 - val_loss: 0.3369 - val_accuracy: 0.8630
Epoch 38/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3397 - accuracy: 0.8595 - val_loss: 0.3383 - val_accuracy: 0.8615
Epoch 39/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3396 - accuracy: 0.8595 - val_loss: 0.3372 - val_accuracy: 0.8615
Epoch 40/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3393 - accuracy: 0.8587 - val_loss: 0.3359 - val_accuracy: 0.8625
Epoch 41/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3390 - accuracy: 0.8614 - val_loss: 0.3356 - val_accuracy: 0.8640
Epoch 42/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3390 - accuracy: 0.8609 - val_loss: 0.3370 - val_accuracy: 0.8630
Epoch 43/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3387 - accuracy: 0.8605 - val_loss: 0.3361 - val_accuracy: 0.8625
Epoch 44/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3385 - accuracy: 0.8601 - val_loss: 0.3372 - val_accuracy: 0.8630
Epoch 45/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3386 - accuracy: 0.8586 - val_loss: 0.3357 - val_accuracy: 0.8610
Epoch 46/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3385 - accuracy: 0.8610 - val_loss: 0.3351 - val_accuracy: 0.8630
Epoch 47/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3385 - accuracy: 0.8609 - val_loss: 0.3353 - val_accuracy: 0.8605
Epoch 48/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3380 - accuracy: 0.8609 - val_loss: 0.3361 - val_accuracy: 0.8615
Epoch 49/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3383 - accuracy: 0.8599 - val_loss: 0.3350 - val_accuracy: 0.8625
Epoch 50/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3381 - accuracy: 0.8616 - val_loss: 0.3352 - val_accuracy: 0.8635
Epoch 51/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3381 - accuracy: 0.8602 - val_loss: 0.3362 - val_accuracy: 0.8610
Epoch 52/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3379 - accuracy: 0.8605 - val_loss: 0.3365 - val_accuracy: 0.8615
Epoch 53/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3376 - accuracy: 0.8615 - val_loss: 0.3363 - val_accuracy: 0.8600
Epoch 54/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3379 - accuracy: 0.8604 - val_loss: 0.3351 - val_accuracy: 0.8615
Epoch 55/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3377 - accuracy: 0.8595 - val_loss: 0.3358 - val_accuracy: 0.8605
Epoch 56/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3376 - accuracy: 0.8606 - val_loss: 0.3355 - val_accuracy: 0.8620
Epoch 57/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3376 - accuracy: 0.8580 - val_loss: 0.3360 - val_accuracy: 0.8620
Epoch 58/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3375 - accuracy: 0.8601 - val_loss: 0.3358 - val_accuracy: 0.8630
Epoch 59/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3375 - accuracy: 0.8612 - val_loss: 0.3362 - val_accuracy: 0.8615
Epoch 60/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3374 - accuracy: 0.8614 - val_loss: 0.3349 - val_accuracy: 0.8590
Epoch 61/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3374 - accuracy: 0.8611 - val_loss: 0.3352 - val_accuracy: 0.8625
Epoch 62/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3371 - accuracy: 0.8605 - val_loss: 0.3356 - val_accuracy: 0.8630
Epoch 63/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3372 - accuracy: 0.8599 - val_loss: 0.3344 - val_accuracy: 0.8605
Epoch 64/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3373 - accuracy: 0.8601 - val_loss: 0.3355 - val_accuracy: 0.8615
Epoch 65/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3372 - accuracy: 0.8591 - val_loss: 0.3355 - val_accuracy: 0.8600
Epoch 66/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3372 - accuracy: 0.8586 - val_loss: 0.3350 - val_accuracy: 0.8600
Epoch 67/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3371 - accuracy: 0.8609 - val_loss: 0.3342 - val_accuracy: 0.8595
Epoch 68/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3371 - accuracy: 0.8594 - val_loss: 0.3346 - val_accuracy: 0.8600
Epoch 69/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3370 - accuracy: 0.8606 - val_loss: 0.3350 - val_accuracy: 0.8600
Epoch 70/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3371 - accuracy: 0.8597 - val_loss: 0.3353 - val_accuracy: 0.8615
Epoch 71/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3370 - accuracy: 0.8606 - val_loss: 0.3351 - val_accuracy: 0.8595
Epoch 72/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3371 - accuracy: 0.8591 - val_loss: 0.3348 - val_accuracy: 0.8585
Epoch 73/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3370 - accuracy: 0.8621 - val_loss: 0.3360 - val_accuracy: 0.8600
Epoch 74/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3368 - accuracy: 0.8595 - val_loss: 0.3350 - val_accuracy: 0.8600
Epoch 75/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3369 - accuracy: 0.8609 - val_loss: 0.3358 - val_accuracy: 0.8615
Epoch 76/100
250/250 [==============================] - 1s 4ms/step - loss: 0.3367 - accuracy: 0.8602 - val_loss: 0.3341 - val_accuracy: 0.8590
Epoch 77/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3369 - accuracy: 0.8608 - val_loss: 0.3342 - val_accuracy: 0.8610
Epoch 78/100
250/250 [==============================] - 1s 4ms/step - loss: 0.3368 - accuracy: 0.8595 - val_loss: 0.3342 - val_accuracy: 0.8615
Epoch 79/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3365 - accuracy: 0.8605 - val_loss: 0.3354 - val_accuracy: 0.8605
Epoch 80/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3367 - accuracy: 0.8620 - val_loss: 0.3338 - val_accuracy: 0.8610
Epoch 81/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3365 - accuracy: 0.8608 - val_loss: 0.3349 - val_accuracy: 0.8590
Epoch 82/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3366 - accuracy: 0.8605 - val_loss: 0.3339 - val_accuracy: 0.8575
Epoch 83/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3367 - accuracy: 0.8608 - val_loss: 0.3338 - val_accuracy: 0.8580
Epoch 84/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3366 - accuracy: 0.8602 - val_loss: 0.3355 - val_accuracy: 0.8615
Epoch 85/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3366 - accuracy: 0.8611 - val_loss: 0.3342 - val_accuracy: 0.8620
Epoch 86/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3365 - accuracy: 0.8597 - val_loss: 0.3363 - val_accuracy: 0.8610
Epoch 87/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3366 - accuracy: 0.8614 - val_loss: 0.3340 - val_accuracy: 0.8575
Epoch 88/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3364 - accuracy: 0.8604 - val_loss: 0.3342 - val_accuracy: 0.8600
Epoch 89/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3364 - accuracy: 0.8594 - val_loss: 0.3334 - val_accuracy: 0.8580
Epoch 90/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3365 - accuracy: 0.8601 - val_loss: 0.3341 - val_accuracy: 0.8585
Epoch 91/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3365 - accuracy: 0.8614 - val_loss: 0.3334 - val_accuracy: 0.8590
Epoch 92/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3365 - accuracy: 0.8599 - val_loss: 0.3341 - val_accuracy: 0.8590
Epoch 93/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3365 - accuracy: 0.8611 - val_loss: 0.3354 - val_accuracy: 0.8595
Epoch 94/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3364 - accuracy: 0.8608 - val_loss: 0.3341 - val_accuracy: 0.8590
Epoch 95/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3364 - accuracy: 0.8602 - val_loss: 0.3342 - val_accuracy: 0.8595
Epoch 96/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3363 - accuracy: 0.8612 - val_loss: 0.3338 - val_accuracy: 0.8585
Epoch 97/100
250/250 [==============================] - 1s 4ms/step - loss: 0.3363 - accuracy: 0.8594 - val_loss: 0.3338 - val_accuracy: 0.8615
Epoch 98/100
250/250 [==============================] - 1s 4ms/step - loss: 0.3362 - accuracy: 0.8600 - val_loss: 0.3340 - val_accuracy: 0.8595
Epoch 99/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3362 - accuracy: 0.8589 - val_loss: 0.3343 - val_accuracy: 0.8615
Epoch 100/100
250/250 [==============================] - 1s 4ms/step - loss: 0.3363 - accuracy: 0.8602 - val_loss: 0.3337 - val_accuracy: 0.8580

In [38]:
model.evaluate(xtrain,ytrain)

250/250 [==============================] - 0s 1ms/step - loss: 0.3344 - accuracy: 0.8608

[0.3343718647956848, 0.8607500195503235]

# Regression

In [ ]:
df = pd.read_csv('https://raw.githubusercontent.com/aishwaryamate/Datasets/main/Regression.csv')
df

In [ ]:
x = df.iloc[:,1:]
y = df['price']

In [ ]:
x = sc.fit_transform(x)
x

In [ ]:
xtrain,xtest,ytrain,ytest = train_test_split(x,y,test_size=0.2, random_state=1)

In [ ]:
ann = Sequential()

ann.add(Dense(units=30, activation='relu'))
ann.add(Dense(units=20, activation='relu'))

ann.add(Dense(units=1))

ann.compile(optimizer='adam',loss = 'mse')

ann.fit(xtrain,ytrain, epochs = 100, validation_data = (xtest,ytest))

In [ ]:
yp = ann.predict(xtest)
yp

In [ ]:
from sklearn.metrics import r2_score

In [ ]:
r2_score(ytest,yp)