In [3]:
!pip install -U keras-tuner

Requirement already satisfied: keras-tuner in /usr/local/lib/python3.10/dist-packages (1.4.7)
Requirement already satisfied: keras in /usr/local/lib/python3.10/dist-packages (from keras-tuner) (2.15.0)
Requirement already satisfied: packaging in /usr/local/lib/python3.10/dist-packages (from keras-tuner) (24.1)
Requirement already satisfied: requests in /usr/local/lib/python3.10/dist-packages (from keras-tuner) (2.31.0)
Requirement already satisfied: kt-legacy in /usr/local/lib/python3.10/dist-packages (from keras-tuner) (1.0.5)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests->keras-tuner) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests->keras-tuner) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests->keras-tuner) (2.0.7)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests->keras-tuner) (2024.6.2)

In [4]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from tensorflow.keras import Sequential
import tensorflow as tf
from tensorflow.keras.layers import Dense
import keras_tuner as kf
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import classification_report

In [5]:
df = pd.read_csv('https://raw.githubusercontent.com/aishwaryamate/Datasets/main/Churn_Modelling.csv')

In [6]:
df

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9996,15606229,Obijiaku,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,9997,15569892,Johnstone,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,9998,15584532,Liu,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,9999,15682355,Sabbatini,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
9999,10000,15628319,Walker,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

In [7]:
df.drop(columns = ['RowNumber'	,'CustomerId',	'Surname'], inplace=True)

In [8]:
df

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...
9995,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
9999,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

In [9]:
df = pd.get_dummies(data = df,columns=['Geography','Gender'], dtype = int)
df

,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_France,Geography_Germany,Geography_Spain,Gender_Female,Gender_Male
0,619,42,2,0.00,1,1,1,101348.88,1,1,0,0,1,0
1,608,41,1,83807.86,1,0,1,112542.58,0,0,0,1,1,0
2,502,42,8,159660.80,3,1,0,113931.57,1,1,0,0,1,0
3,699,39,1,0.00,2,0,0,93826.63,0,1,0,0,1,0
4,850,43,2,125510.82,1,1,1,79084.10,0,0,0,1,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,771,39,5,0.00,2,1,0,96270.64,0,1,0,0,0,1
9996,516,35,10,57369.61,1,1,1,101699.77,0,1,0,0,0,1
9997,709,36,7,0.00,1,0,1,42085.58,1,1,0,0,1,0
9998,772,42,3,75075.31,2,1,0,92888.52,1,0,1,0,0,1
9999,792,28,4,130142.79,1,1,0,38190.78,0,1,0,0,1,0

In [10]:
x = df.drop(columns = ['Exited'])
y = df['Exited']

In [11]:
sc = StandardScaler()

x = sc.fit_transform(x)

In [12]:
x

array([[-0.32622142,  0.29351742, -1.04175968, ..., -0.57380915,
         1.09598752, -1.09598752],
       [-0.44003595,  0.19816383, -1.38753759, ...,  1.74273971,
         1.09598752, -1.09598752],
       [-1.53679418,  0.29351742,  1.03290776, ..., -0.57380915,
         1.09598752, -1.09598752],
       ...,
       [ 0.60498839, -0.27860412,  0.68712986, ..., -0.57380915,
         1.09598752, -1.09598752],
       [ 1.25683526,  0.29351742, -0.69598177, ..., -0.57380915,
        -0.91241915,  0.91241915],
       [ 1.46377078, -1.04143285, -0.35020386, ..., -0.57380915,
         1.09598752, -1.09598752]])

In [13]:
from sklearn.model_selection import train_test_split

In [14]:
xtrain,xtest,ytrain,ytest = train_test_split(x,y,test_size = 0.20, random_state=1)

In [16]:
ann = Sequential()

ann.add(Dense(units = 10, activation = 'relu'))
ann.add(Dense(units = 1, activation = 'sigmoid'))

ann.compile(optimizer = 'adadelta', loss = 'binary_crossentropy', metrics ='accuracy')

ann.fit(xtrain,ytrain,epochs = 100)

Epoch 1/100
250/250 [==============================] - 2s 5ms/step - loss: 0.6481 - accuracy: 0.6321
Epoch 2/100
250/250 [==============================] - 0s 2ms/step - loss: 0.6474 - accuracy: 0.6332
Epoch 3/100
250/250 [==============================] - 0s 2ms/step - loss: 0.6468 - accuracy: 0.6338
Epoch 4/100
250/250 [==============================] - 0s 2ms/step - loss: 0.6461 - accuracy: 0.6341
Epoch 5/100
250/250 [==============================] - 0s 2ms/step - loss: 0.6455 - accuracy: 0.6354
Epoch 6/100
250/250 [==============================] - 0s 2ms/step - loss: 0.6448 - accuracy: 0.6360
Epoch 7/100
250/250 [==============================] - 1s 2ms/step - loss: 0.6441 - accuracy: 0.6370
Epoch 8/100
250/250 [==============================] - 0s 2ms/step - loss: 0.6434 - accuracy: 0.6378
Epoch 9/100
250/250 [==============================] - 1s 2ms/step - loss: 0.6428 - accuracy: 0.6390
Epoch 10/100
250/250 [==============================] - 1s 3ms/step - loss: 0.6421 - accuracy: 0.6403
Epoch 11/100
250/250 [==============================] - 1s 3ms/step - loss: 0.6414 - accuracy: 0.6416
Epoch 12/100
250/250 [==============================] - 1s 3ms/step - loss: 0.6408 - accuracy: 0.6428
Epoch 13/100
250/250 [==============================] - 1s 3ms/step - loss: 0.6401 - accuracy: 0.6436
Epoch 14/100
250/250 [==============================] - 1s 3ms/step - loss: 0.6395 - accuracy: 0.6446
Epoch 15/100
250/250 [==============================] - 0s 2ms/step - loss: 0.6388 - accuracy: 0.6450
Epoch 16/100
250/250 [==============================] - 0s 2ms/step - loss: 0.6382 - accuracy: 0.6461
Epoch 17/100
250/250 [==============================] - 1s 2ms/step - loss: 0.6375 - accuracy: 0.6467
Epoch 18/100
250/250 [==============================] - 1s 2ms/step - loss: 0.6369 - accuracy: 0.6476
Epoch 19/100
250/250 [==============================] - 1s 2ms/step - loss: 0.6362 - accuracy: 0.6484
Epoch 20/100
250/250 [==============================] - 1s 2ms/step - loss: 0.6356 - accuracy: 0.6490
Epoch 21/100
250/250 [==============================] - 1s 2ms/step - loss: 0.6350 - accuracy: 0.6495
Epoch 22/100
250/250 [==============================] - 1s 2ms/step - loss: 0.6343 - accuracy: 0.6500
Epoch 23/100
250/250 [==============================] - 1s 2ms/step - loss: 0.6337 - accuracy: 0.6503
Epoch 24/100
250/250 [==============================] - 0s 2ms/step - loss: 0.6331 - accuracy: 0.6506
Epoch 25/100
250/250 [==============================] - 0s 2ms/step - loss: 0.6324 - accuracy: 0.6507
Epoch 26/100
250/250 [==============================] - 0s 2ms/step - loss: 0.6318 - accuracy: 0.6518
Epoch 27/100
250/250 [==============================] - 0s 2ms/step - loss: 0.6312 - accuracy: 0.6520
Epoch 28/100
250/250 [==============================] - 0s 2ms/step - loss: 0.6306 - accuracy: 0.6528
Epoch 29/100
250/250 [==============================] - 0s 2ms/step - loss: 0.6299 - accuracy: 0.6534
Epoch 30/100
250/250 [==============================] - 1s 2ms/step - loss: 0.6293 - accuracy: 0.6536
Epoch 31/100
250/250 [==============================] - 0s 2ms/step - loss: 0.6287 - accuracy: 0.6546
Epoch 32/100
250/250 [==============================] - 1s 2ms/step - loss: 0.6281 - accuracy: 0.6553
Epoch 33/100
250/250 [==============================] - 0s 2ms/step - loss: 0.6275 - accuracy: 0.6559
Epoch 34/100
250/250 [==============================] - 1s 2ms/step - loss: 0.6269 - accuracy: 0.6566
Epoch 35/100
250/250 [==============================] - 1s 3ms/step - loss: 0.6263 - accuracy: 0.6576
Epoch 36/100
250/250 [==============================] - 1s 3ms/step - loss: 0.6256 - accuracy: 0.6585
Epoch 37/100
250/250 [==============================] - 1s 3ms/step - loss: 0.6250 - accuracy: 0.6589
Epoch 38/100
250/250 [==============================] - 1s 3ms/step - loss: 0.6245 - accuracy: 0.6595
Epoch 39/100
250/250 [==============================] - 1s 5ms/step - loss: 0.6239 - accuracy: 0.6603
Epoch 40/100
250/250 [==============================] - 2s 6ms/step - loss: 0.6233 - accuracy: 0.6597
Epoch 41/100
250/250 [==============================] - 2s 7ms/step - loss: 0.6227 - accuracy: 0.6603
Epoch 42/100
250/250 [==============================] - 2s 6ms/step - loss: 0.6221 - accuracy: 0.6620
Epoch 43/100
250/250 [==============================] - 2s 7ms/step - loss: 0.6215 - accuracy: 0.6629
Epoch 44/100
250/250 [==============================] - 1s 6ms/step - loss: 0.6209 - accuracy: 0.6633
Epoch 45/100
250/250 [==============================] - 2s 9ms/step - loss: 0.6203 - accuracy: 0.6645
Epoch 46/100
250/250 [==============================] - 1s 3ms/step - loss: 0.6198 - accuracy: 0.6654
Epoch 47/100
250/250 [==============================] - 1s 3ms/step - loss: 0.6192 - accuracy: 0.6670
Epoch 48/100
250/250 [==============================] - 1s 3ms/step - loss: 0.6186 - accuracy: 0.6683
Epoch 49/100
250/250 [==============================] - 1s 4ms/step - loss: 0.6181 - accuracy: 0.6689
Epoch 50/100
250/250 [==============================] - 1s 3ms/step - loss: 0.6175 - accuracy: 0.6695
Epoch 51/100
250/250 [==============================] - 1s 2ms/step - loss: 0.6169 - accuracy: 0.6699
Epoch 52/100
250/250 [==============================] - 0s 2ms/step - loss: 0.6164 - accuracy: 0.6708
Epoch 53/100
250/250 [==============================] - 0s 2ms/step - loss: 0.6158 - accuracy: 0.6716
Epoch 54/100
250/250 [==============================] - 0s 2ms/step - loss: 0.6152 - accuracy: 0.6725
Epoch 55/100
250/250 [==============================] - 1s 2ms/step - loss: 0.6147 - accuracy: 0.6739
Epoch 56/100
250/250 [==============================] - 0s 2ms/step - loss: 0.6141 - accuracy: 0.6741
Epoch 57/100
250/250 [==============================] - 1s 2ms/step - loss: 0.6136 - accuracy: 0.6754
Epoch 58/100
250/250 [==============================] - 0s 2ms/step - loss: 0.6130 - accuracy: 0.6759
Epoch 59/100
250/250 [==============================] - 1s 2ms/step - loss: 0.6125 - accuracy: 0.6762
Epoch 60/100
250/250 [==============================] - 1s 2ms/step - loss: 0.6120 - accuracy: 0.6773
Epoch 61/100
250/250 [==============================] - 1s 2ms/step - loss: 0.6114 - accuracy: 0.6777
Epoch 62/100
250/250 [==============================] - 0s 2ms/step - loss: 0.6109 - accuracy: 0.6787
Epoch 63/100
250/250 [==============================] - 1s 2ms/step - loss: 0.6103 - accuracy: 0.6800
Epoch 64/100
250/250 [==============================] - 0s 2ms/step - loss: 0.6098 - accuracy: 0.6806
Epoch 65/100
250/250 [==============================] - 0s 2ms/step - loss: 0.6093 - accuracy: 0.6814
Epoch 66/100
250/250 [==============================] - 1s 2ms/step - loss: 0.6088 - accuracy: 0.6817
Epoch 67/100
250/250 [==============================] - 0s 2ms/step - loss: 0.6083 - accuracy: 0.6824
Epoch 68/100
250/250 [==============================] - 0s 2ms/step - loss: 0.6077 - accuracy: 0.6833
Epoch 69/100
250/250 [==============================] - 1s 2ms/step - loss: 0.6072 - accuracy: 0.6842
Epoch 70/100
250/250 [==============================] - 1s 3ms/step - loss: 0.6067 - accuracy: 0.6851
Epoch 71/100
250/250 [==============================] - 1s 4ms/step - loss: 0.6062 - accuracy: 0.6860
Epoch 72/100
250/250 [==============================] - 1s 4ms/step - loss: 0.6057 - accuracy: 0.6867
Epoch 73/100
250/250 [==============================] - 1s 4ms/step - loss: 0.6052 - accuracy: 0.6873
Epoch 74/100
250/250 [==============================] - 1s 4ms/step - loss: 0.6046 - accuracy: 0.6879
Epoch 75/100
250/250 [==============================] - 1s 3ms/step - loss: 0.6041 - accuracy: 0.6883
Epoch 76/100
250/250 [==============================] - 1s 2ms/step - loss: 0.6036 - accuracy: 0.6885
Epoch 77/100
250/250 [==============================] - 1s 2ms/step - loss: 0.6031 - accuracy: 0.6892
Epoch 78/100
250/250 [==============================] - 1s 2ms/step - loss: 0.6026 - accuracy: 0.6900
Epoch 79/100
250/250 [==============================] - 0s 2ms/step - loss: 0.6021 - accuracy: 0.6901
Epoch 80/100
250/250 [==============================] - 1s 2ms/step - loss: 0.6016 - accuracy: 0.6906
Epoch 81/100
250/250 [==============================] - 1s 2ms/step - loss: 0.6012 - accuracy: 0.6914
Epoch 82/100
250/250 [==============================] - 0s 2ms/step - loss: 0.6007 - accuracy: 0.6917
Epoch 83/100
250/250 [==============================] - 1s 2ms/step - loss: 0.6002 - accuracy: 0.6923
Epoch 84/100
250/250 [==============================] - 0s 2ms/step - loss: 0.5997 - accuracy: 0.6927
Epoch 85/100
250/250 [==============================] - 1s 2ms/step - loss: 0.5992 - accuracy: 0.6934
Epoch 86/100
250/250 [==============================] - 0s 2ms/step - loss: 0.5987 - accuracy: 0.6938
Epoch 87/100
250/250 [==============================] - 1s 2ms/step - loss: 0.5983 - accuracy: 0.6944
Epoch 88/100
250/250 [==============================] - 1s 2ms/step - loss: 0.5978 - accuracy: 0.6956
Epoch 89/100
250/250 [==============================] - 1s 2ms/step - loss: 0.5973 - accuracy: 0.6960
Epoch 90/100
250/250 [==============================] - 1s 2ms/step - loss: 0.5968 - accuracy: 0.6964
Epoch 91/100
250/250 [==============================] - 1s 2ms/step - loss: 0.5964 - accuracy: 0.6966
Epoch 92/100
250/250 [==============================] - 1s 2ms/step - loss: 0.5959 - accuracy: 0.6973
Epoch 93/100
250/250 [==============================] - 1s 3ms/step - loss: 0.5954 - accuracy: 0.6977
Epoch 94/100
250/250 [==============================] - 1s 3ms/step - loss: 0.5949 - accuracy: 0.6984
Epoch 95/100
250/250 [==============================] - 1s 3ms/step - loss: 0.5945 - accuracy: 0.6991
Epoch 96/100
250/250 [==============================] - 1s 3ms/step - loss: 0.5940 - accuracy: 0.7000
Epoch 97/100
250/250 [==============================] - 1s 4ms/step - loss: 0.5936 - accuracy: 0.7007
Epoch 98/100
250/250 [==============================] - 1s 3ms/step - loss: 0.5931 - accuracy: 0.7014
Epoch 99/100
250/250 [==============================] - 0s 2ms/step - loss: 0.5927 - accuracy: 0.7024
Epoch 100/100
250/250 [==============================] - 0s 2ms/step - loss: 0.5922 - accuracy: 0.7024

In [17]:
ypred = ann.predict(xtest)
ypred = ypred > 0.5
ypred

63/63 [==============================] - 0s 1ms/step

array([[False],
       [ True],
       [False],
       ...,
       [False],
       [False],
       [ True]])

In [18]:
print(classification_report(ytest, ypred))

              precision    recall  f1-score   support

           0       0.81      0.82      0.82      1585
           1       0.29      0.28      0.28       415

    accuracy                           0.71      2000
   macro avg       0.55      0.55      0.55      2000
weighted avg       0.70      0.71      0.71      2000

In [19]:
ann.evaluate(xtrain,ytrain)

250/250 [==============================] - 1s 2ms/step - loss: 0.5920 - accuracy: 0.7028

[0.5919739603996277, 0.702750027179718]

# Hyperparameter tuning

In [20]:
counter = 0

for i in range(0,3):
  if counter == 0:
    print('Python')

else:
    print('Machine learning')

Python
Python
Python
Machine learning

In [ ]:
for i in range(0,3):
  print('Python')

print('Machine learning')

In [ ]:
i = 1

'units'+str(i)

In [ ]:
list(range(8,128,8))

In [21]:
def hyper(hp): #This defines a function named hyper that takes a single argument hp.
    model = Sequential()
    counter = 0 #Initializes a counter variable to keep track of the current layer being added to the model.
    for i in range(hp.Int('num_layers', min_value = 1,max_value=10)):  #Loops through a range of layers, where the number of layers is a hyperparameter named 'num_layers' with a minimum value of 1 and a maximum value of 10.
        if counter ==0:
            model.add(Dense(hp.Int('units'+str(i),min_value=8,max_value=128,step=8),
                            activation = hp.Choice('activation'+str(i),values = ['relu','tanh','sigmoid']),
                            input_dim = 13)) #Adds the first layer with input dimensions specified by input_dim=13. The number of units ('units') and activation function ('activation') are hyperparameters, and their values are determined by the hp object.
    else:
          model.add(Dense(
              hp.Int('units'+str(i),min_value=8,max_value=128,step=8),
              activation = hp.Choice('activation'+str(i),values = ['relu','tanh','sigmoid'])))  #Adds subsequent layers (after the first layer) with hyperparameter-specified units and activation functions.
    counter+=1   #Increments the counter to keep track of the layers added.
    model.add(Dense(units = 1,activation='sigmoid'))   #Adds the output layer with a single unit and sigmoid activation function, typical for binary classification problems.
    model.compile(optimizer = hp.Choice('optimizer',values = ['adam','rmsprop','sgd']),
                loss = 'binary_crossentropy',metrics = 'accuracy')
    return model  #Returns the compiled model.

In [22]:
tuner = kf.RandomSearch(hyper,
                        objective = 'val_accuracy',
                        max_trials = 3)

In [23]:
tuner.search(xtrain,ytrain,epochs = 5, validation_data = (xtest,ytest))

Trial 3 Complete [00h 00m 11s]
val_accuracy: 0.7925000190734863

Best val_accuracy So Far: 0.809499979019165
Total elapsed time: 00h 00m 30s

In [24]:
tuner.get_best_hyperparameters()[0].values

{'num_layers': 3,
 'units0': 80,
 'activation0': 'sigmoid',
 'optimizer': 'adam',
 'units1': 24,
 'activation1': 'sigmoid',
 'units2': 72,
 'activation2': 'sigmoid',
 'units3': 80,
 'activation3': 'relu',
 'units4': 96,
 'activation4': 'relu',
 'units5': 48,
 'activation5': 'tanh',
 'units6': 16,
 'activation6': 'relu',
 'units7': 88,
 'activation7': 'sigmoid'}

In [ ]:
x.shape

In [25]:
tuned_model = tuner.get_best_models(num_models=1)[0]

In [26]:
tuned_model.fit(xtrain,ytrain,epochs=50, validation_data=(xtest,ytest))

Epoch 1/50
250/250 [==============================] - 4s 10ms/step - loss: 0.4303 - accuracy: 0.8010 - val_loss: 0.4212 - val_accuracy: 0.8090
Epoch 2/50
250/250 [==============================] - 2s 7ms/step - loss: 0.4308 - accuracy: 0.8019 - val_loss: 0.4333 - val_accuracy: 0.7945
Epoch 3/50
250/250 [==============================] - 2s 7ms/step - loss: 0.4306 - accuracy: 0.8049 - val_loss: 0.4210 - val_accuracy: 0.8045
Epoch 4/50
250/250 [==============================] - 2s 6ms/step - loss: 0.4281 - accuracy: 0.8094 - val_loss: 0.4263 - val_accuracy: 0.8000
Epoch 5/50
250/250 [==============================] - 2s 8ms/step - loss: 0.4273 - accuracy: 0.8095 - val_loss: 0.4232 - val_accuracy: 0.8130
Epoch 6/50
250/250 [==============================] - 2s 9ms/step - loss: 0.4253 - accuracy: 0.8173 - val_loss: 0.4222 - val_accuracy: 0.8100
Epoch 7/50
250/250 [==============================] - 2s 7ms/step - loss: 0.4223 - accuracy: 0.8165 - val_loss: 0.4150 - val_accuracy: 0.8225
Epoch 8/50
250/250 [==============================] - 1s 3ms/step - loss: 0.4186 - accuracy: 0.8232 - val_loss: 0.4094 - val_accuracy: 0.8295
Epoch 9/50
250/250 [==============================] - 1s 4ms/step - loss: 0.4156 - accuracy: 0.8249 - val_loss: 0.4063 - val_accuracy: 0.8280
Epoch 10/50
250/250 [==============================] - 1s 4ms/step - loss: 0.4132 - accuracy: 0.8288 - val_loss: 0.4034 - val_accuracy: 0.8340
Epoch 11/50
250/250 [==============================] - 1s 3ms/step - loss: 0.4095 - accuracy: 0.8304 - val_loss: 0.4118 - val_accuracy: 0.8235
Epoch 12/50
250/250 [==============================] - 1s 3ms/step - loss: 0.4066 - accuracy: 0.8319 - val_loss: 0.4014 - val_accuracy: 0.8360
Epoch 13/50
250/250 [==============================] - 1s 4ms/step - loss: 0.4036 - accuracy: 0.8355 - val_loss: 0.3953 - val_accuracy: 0.8330
Epoch 14/50
250/250 [==============================] - 1s 3ms/step - loss: 0.4006 - accuracy: 0.8328 - val_loss: 0.3926 - val_accuracy: 0.8365
Epoch 15/50
250/250 [==============================] - 1s 3ms/step - loss: 0.3967 - accuracy: 0.8355 - val_loss: 0.3893 - val_accuracy: 0.8380
Epoch 16/50
250/250 [==============================] - 1s 3ms/step - loss: 0.3949 - accuracy: 0.8393 - val_loss: 0.3821 - val_accuracy: 0.8425
Epoch 17/50
250/250 [==============================] - 1s 3ms/step - loss: 0.3898 - accuracy: 0.8403 - val_loss: 0.3785 - val_accuracy: 0.8430
Epoch 18/50
250/250 [==============================] - 1s 3ms/step - loss: 0.3846 - accuracy: 0.8436 - val_loss: 0.3727 - val_accuracy: 0.8510
Epoch 19/50
250/250 [==============================] - 1s 3ms/step - loss: 0.3779 - accuracy: 0.8428 - val_loss: 0.3691 - val_accuracy: 0.8525
Epoch 20/50
250/250 [==============================] - 1s 5ms/step - loss: 0.3735 - accuracy: 0.8468 - val_loss: 0.3619 - val_accuracy: 0.8495
Epoch 21/50
250/250 [==============================] - 1s 6ms/step - loss: 0.3634 - accuracy: 0.8516 - val_loss: 0.3553 - val_accuracy: 0.8515
Epoch 22/50
250/250 [==============================] - 1s 6ms/step - loss: 0.3595 - accuracy: 0.8530 - val_loss: 0.3476 - val_accuracy: 0.8580
Epoch 23/50
250/250 [==============================] - 1s 4ms/step - loss: 0.3519 - accuracy: 0.8564 - val_loss: 0.3445 - val_accuracy: 0.8590
Epoch 24/50
250/250 [==============================] - 1s 3ms/step - loss: 0.3466 - accuracy: 0.8576 - val_loss: 0.3419 - val_accuracy: 0.8580
Epoch 25/50
250/250 [==============================] - 1s 3ms/step - loss: 0.3441 - accuracy: 0.8572 - val_loss: 0.3563 - val_accuracy: 0.8530
Epoch 26/50
250/250 [==============================] - 1s 4ms/step - loss: 0.3404 - accuracy: 0.8636 - val_loss: 0.3415 - val_accuracy: 0.8610
Epoch 27/50
250/250 [==============================] - 1s 3ms/step - loss: 0.3428 - accuracy: 0.8564 - val_loss: 0.3360 - val_accuracy: 0.8605
Epoch 28/50
250/250 [==============================] - 1s 3ms/step - loss: 0.3418 - accuracy: 0.8602 - val_loss: 0.3363 - val_accuracy: 0.8655
Epoch 29/50
250/250 [==============================] - 1s 3ms/step - loss: 0.3382 - accuracy: 0.8621 - val_loss: 0.3386 - val_accuracy: 0.8600
Epoch 30/50
250/250 [==============================] - 1s 3ms/step - loss: 0.3377 - accuracy: 0.8614 - val_loss: 0.3333 - val_accuracy: 0.8620
Epoch 31/50
250/250 [==============================] - 1s 4ms/step - loss: 0.3377 - accuracy: 0.8604 - val_loss: 0.3338 - val_accuracy: 0.8625
Epoch 32/50
250/250 [==============================] - 1s 4ms/step - loss: 0.3382 - accuracy: 0.8590 - val_loss: 0.3331 - val_accuracy: 0.8625
Epoch 33/50
250/250 [==============================] - 1s 3ms/step - loss: 0.3356 - accuracy: 0.8626 - val_loss: 0.3353 - val_accuracy: 0.8635
Epoch 34/50
250/250 [==============================] - 1s 5ms/step - loss: 0.3354 - accuracy: 0.8620 - val_loss: 0.3408 - val_accuracy: 0.8600
Epoch 35/50
250/250 [==============================] - 2s 7ms/step - loss: 0.3323 - accuracy: 0.8616 - val_loss: 0.3338 - val_accuracy: 0.8660
Epoch 36/50
250/250 [==============================] - 2s 7ms/step - loss: 0.3330 - accuracy: 0.8594 - val_loss: 0.3350 - val_accuracy: 0.8645
Epoch 37/50
250/250 [==============================] - 2s 7ms/step - loss: 0.3325 - accuracy: 0.8624 - val_loss: 0.3393 - val_accuracy: 0.8590
Epoch 38/50
250/250 [==============================] - 1s 5ms/step - loss: 0.3326 - accuracy: 0.8633 - val_loss: 0.3322 - val_accuracy: 0.8655
Epoch 39/50
250/250 [==============================] - 1s 3ms/step - loss: 0.3348 - accuracy: 0.8597 - val_loss: 0.3376 - val_accuracy: 0.8630
Epoch 40/50
250/250 [==============================] - 1s 3ms/step - loss: 0.3318 - accuracy: 0.8624 - val_loss: 0.3430 - val_accuracy: 0.8635
Epoch 41/50
250/250 [==============================] - 1s 3ms/step - loss: 0.3323 - accuracy: 0.8614 - val_loss: 0.3317 - val_accuracy: 0.8635
Epoch 42/50
250/250 [==============================] - 1s 4ms/step - loss: 0.3306 - accuracy: 0.8626 - val_loss: 0.3456 - val_accuracy: 0.8565
Epoch 43/50
250/250 [==============================] - 1s 4ms/step - loss: 0.3297 - accuracy: 0.8620 - val_loss: 0.3401 - val_accuracy: 0.8615
Epoch 44/50
250/250 [==============================] - 1s 3ms/step - loss: 0.3314 - accuracy: 0.8629 - val_loss: 0.3629 - val_accuracy: 0.8550
Epoch 45/50
250/250 [==============================] - 1s 3ms/step - loss: 0.3329 - accuracy: 0.8619 - val_loss: 0.3304 - val_accuracy: 0.8665
Epoch 46/50
250/250 [==============================] - 1s 4ms/step - loss: 0.3289 - accuracy: 0.8620 - val_loss: 0.3387 - val_accuracy: 0.8605
Epoch 47/50
250/250 [==============================] - 1s 4ms/step - loss: 0.3293 - accuracy: 0.8606 - val_loss: 0.3304 - val_accuracy: 0.8675
Epoch 48/50
250/250 [==============================] - 1s 4ms/step - loss: 0.3292 - accuracy: 0.8622 - val_loss: 0.3340 - val_accuracy: 0.8610
Epoch 49/50
250/250 [==============================] - 1s 6ms/step - loss: 0.3283 - accuracy: 0.8644 - val_loss: 0.3336 - val_accuracy: 0.8625
Epoch 50/50
250/250 [==============================] - 2s 6ms/step - loss: 0.3281 - accuracy: 0.8664 - val_loss: 0.3341 - val_accuracy: 0.8630

In [27]:
tuned_model.evaluate(xtrain,ytrain)

250/250 [==============================] - 1s 3ms/step - loss: 0.3273 - accuracy: 0.8635

[0.32730692625045776, 0.8634999990463257]

In [28]:
tuned_model.evaluate(xtest,ytest)

63/63 [==============================] - 0s 4ms/step - loss: 0.3341 - accuracy: 0.8630

[0.3341153562068939, 0.8629999756813049]